apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: simple-app
    app.kubernetes.io/part-of: app-simple-app
  name: simple-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-app
      app.kubernetes.io/part-of: app-simple-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: simple-app
        app.kubernetes.io/part-of: app-simple-app
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: simple-app
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
