apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAWjw+SCj5g1eFKbZNST+Z3yu0c6MTnYWH6Wblv8gCv1kjWxbmrvBDbXRU0OeMefmE5Kg8l+3UOE/jMxAL4C37x0CbMoRoGvz+U8cmskCDG5L0mdnrCs1ngxo0OxU8eX3q368YEESOQXADIEH/MeQ48S0xFbcxJtRW8/5ti5HbFEeUYuNbSRwm2VLn0vMNSGttzBI6XoeVrxwWXSkYDAB8GtCkVMaGXqfpbfAk123Tz7ZKxXAqdsVY/K9M2hK/6QQQQxhvzgkppquJaRkOWPFM0jtt+hlXK51vd2mVTLTrnLVQAU5ZGSlGEgr5rPGvsNDEBMYmCvimvan6IuYTJhGicayg2PLMz+KaTN5vbpGVSkjsqF0p6GY/WcE9IuODD4wF+SUnvR6Z9RpcdQMdjpwvqiyBU7NXPLc+tOoZ26OFCs+pQ4jvzEl0nyJcJMY+7jDOdm1f2ol6Pw1YSLZNyLA3vmrKer1AxJqX+tSXHAKMw3EOCAy93yGT3hUmCHPU6A2QYHHqCfJ/lU5lppTHYyM7tpVibHHGWIggKCzK4dgwmk/JntpXedCWKUv7Ot4/LUTbby/xP7RxtTQbxZGS7YdB1kaBiuhp0uSrEZp1J6JR9nJG0Mu9eX2wqxBUT4Xu3QXxA7UCbcSYaW1aazMEf9/w9Nerh0eAD65sq9BYCUVR77kKaxXimv1jgZzNPhBATQRNJeMD9g/BwSKmcCgpzfpYomSm5UQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
