apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-simple-app
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCImY+5+9LkPT1wrBbsKLXhxe0QhIZG2qHR/ooqTO6CXWgYfZfW1ftIAwXmF3Fj7/rkSziS1h66EVw672YtNNazoJIHsYiWse6z4KGDr5ifrBrrTcW0fuWVjEvbvzFN9ZGr/PtvckFSjMKDvm1uVc13U0JzsBUrFnIydYVOcHZZUNxeUSWRYxEYnkypItOjxryv8f+YXxTSfAbh1IklM3q6bYHPrVS/SRx2+4T04KqDrSchyFS4d/nT3M0r/AmY61sZ9TGT0ejTc6R9TrqW4MB/R6MLQAyUzWTGgMOaV13n7qL2Bnjf2TZydQUh8MFwIG9nHX3gMPWkq7oxYJno4gW655O2ucAh9VxDXkoRUXNzSfpyVzjGMVvFmAdPXuyPo89o/Hm44BEz9I+PqIASsu8+YcZaGLrHMGrAaj/LBVmSQubR15gQ9mMQOe84cKzNdKFrShfIjhSuB0JF7zEOsggGxc79dTpsCSGVbrWJfuqssXjmXWQDeFg6IkdAPW8kbzzJDhyD55+9IHN4gJL7SxBJzeKGAJ9EJCbU/IscqKDpKQMITbSBl/svcQGTKWZhl/hQ15HdHuWP7ykm+/MTwWpjugiJji5my7S8KVDL9g+wWyiomLs5Hqle6CE8uagT9G42ne0guN9piXJgGP7fXgx4+8mxbk/6a1RF1Vngv+dfwahJtDC3dEVssmJruQ3/Pa6BLjCiw66P1IM3vicm41nFixtbAQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-simple-app
      namespace: cicd
    type: Opaque
